version: '2'
services:
  gestor_contenidos_service:
    image: eventos/content:latest
    expose:
      - 80
    environment:
        - MYSQL_HOTELES_USER=${MYSQL_HOTELES_USER}      
        - MYSQL_HOTELES_PASSWORD=${MYSQL_HOTELES_PASSWORD}      
        - MYSQL_HOTELES_CONECTION=${MYSQL_HOTELES_CONECTION}              
        - MYSQL_HOTELES_CONECTION_PHP=${MYSQL_HOTELES_CONECTION_PHP}              
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - network
    volumes: 
      - ./:/var/www/html
    restart: always
  proxy_service:
    image:  colsubsidioproxy/content-proxy:eventos
    ports:
      - 80:80
    build:
     context: ../proxys/gestor-contenidos-proxy
     dockerfile: ./Dockerfile
    networks:
      - network 
    volumes:
      - proxy_config:/etc/nginx
      - proxy_logs:/var/log
    restart: always      
volumes:
  gestor_dist:
  proxy_config:
  proxy_logs:
networks:
  network:    

   
