version: '2'
services:
  gestor_contenidos_service:
    image: eventos/content:latest
    ports:
      - 80:80
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - network
    volumes: 
      - gestor_dist:/var/www/html/gestor
    restart: always
  proxy_service:
    image:  colsubsidioproxy/content-proxy:eventos
    ports:
      - 90:80
    build:
     context: ../proxys/gestor-contenidos-proxy
     dockerfile: ./Dockerfile
    networks:
      - network 
    volumes:
      - proxy_config:/etc/nginx
      - proxy_logs:/var/log
    restart: always      
volumes:
  gestor_dist:
  proxy_config:
  proxy_logs:
networks:
  network:    

   
