version: '3.5'
services:
 gestor_contenidos_service:
    container_name: hotels-gestor-contenidos
    image:  crishubprojects/hotels-gestor-contenidos:latest
    expose:
      - "8081:81"
    build:
      context: ./hotels-gestor-contenidos
      dockerfile: ./Dockerfile
    networks:
      - network  
    volumes: 
      - ./hotels-gestor-contenidos:/var/www/html/gestor
    restart: always  
    environment:
      - "TZ=America/Bogota"   

networks:
  network:      